[package]
name = "bootrom-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootrom-pac = {path = "./pac"}
riscv = "0.7"
embedded-hal = "=1.0.0-alpha.7"
heapless = "0.7"